# Generated by Django 5.1.4 on 2025-02-04 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.URLField()),
                ('gender', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=20)),
                ('species', models.CharField(max_length=50)),
                ('resource', models.CharField(max_length=20)),
                ('range_type', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=50)),
                ('release_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Homepage', max_length=255)),
            ],
        ),
    ]
